DROP TABLE IF EXISTS authenticity_settings;
DROP TABLE IF EXISTS code_revokations;
DROP TABLE IF EXISTS ownership_claims;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS ownership_codes;
DROP TABLE IF EXISTS manufacturers;
DROP TABLE IF EXISTS users_info;
DROP TABLE IF EXISTS contracts;
DROP TABLE IF EXISTS certificates